const projects = [
  {
    index: 1,
    name: "Super Beach Cleanup",
    coverImage: "/Projects/Super-Beach-Cleanup/Cover.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    startDate: "2023-06-24",
    endDate: "2023-06-24",
    status: "finished",
  },
  {
    index: 2,
    name: "Puppy Therapy",
    coverImage: "/Projects/Puppy-Therapy/Cover.jpg",
    description: "Nulla facilisi. Sed euismod nisl sit amet magna consectetur.",
    startDate: "2023-06-24",
    endDate: "2023-06-24",
    status: "finished",
  },
  {
    index: 3,
    name: "Music Camp",
    coverImage: "/Projects/Music-Camp/Cover.jpeg",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-07-15",
    endDate: "2023-07-15",
    status: "upcoming",
  },
  {
    index: 4,
    name: "Art Camp",
    coverImage: "/Projects/Art-Camp/Cover.webp",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-07-22",
    endDate: "2023-07-22",
    status: "upcoming",
  },
  {
    index: 5,
    name: "Great Vancouver Food Bank Fundraiser",
    coverImage: "/Projects/Great-Vancouver-Food-Bank-Fundraiser/Cover.jpg",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-07-29",
    endDate: "2023-07-29",
    status: "upcoming",
  },
  {
    index: 6,
    name: "Soccer Camp",
    coverImage: "/Projects/Soccer-Camp/Cover.webp",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-08-12",
    endDate: "2023-08-12",
    status: "upcoming",
  },
  {
    index: 7,
    name: "Bike For Cancer Fundraiser",
    coverImage: "/Projects/Bike-For-Cancer-Fundraiser/Cover.jpg",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-09-02",
    endDate: "2023-09-02",
    status: "upcoming",
  },
  {
    index: 8,
    name: "Scholarship and Grant-Writing Workshop",
    coverImage: "/Projects/Scholarship-and-Grant-Writing-Workshop/Cover.jpg",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-09-09",
    endDate: "2023-09-09",
    status: "upcoming",
  },
  {
    index: 9,
    name: "Sustainability Panel",
    coverImage: "/Projects/Sustainability-Panel/Cover.jpeg",
    description: "Vestibulum interdum diam a urna fermentum tempor.",
    startDate: "2023-09-30",
    endDate: "2023-09-30",
    status: "upcoming",
  },
];
export default projects;
