const members = [
  {
    index: 1,
    name: "Aaliyah",
    imageAddress: "/Members/Aaliyah.jpg",
    Roles: "Project director",
    phone: "",
    email: "",
  },
  {
    index: 2,
    name: "Sobhan",
    imageAddress: "/Members/Sobhan.jpg",
    Roles: "Admin director, finance lead",
    phone: "",
    email: "",
  },
  {
    index: 3,
    name: "Sahba",
    imageAddress: "/Members/Sahba.jpg",
    Roles: "Marketing director",
    phone: "",
    email: "",
  },
  {
    index: 4,
    name: "Adib",
    imageAddress: "/Members/Adib.jpg",
    Roles: "Content director, graphic designer",
    phone: "",
    email: "",
  },
  {
    index: 5,
    name: "Noora",
    imageAddress: "/Members/Noora.jpg",
    Roles: "Multi-media manager, outreach lead",
    phone: "",
    email: "",
  },
  {
    index: 6,
    name: "Roham",
    imageAddress: "/Members/Roham.jpeg",
    Roles: "IT lead",
    phone: "",
    email: "",
  },
  {
    index: 7,
    name: "Romina",
    imageAddress: "/Members/Romina.jpg",
    Roles: "Communications lead, social media lead",
    phone: "",
    email: "",
  },
  {
    index: 8,
    name: "Carmel",
    imageAddress: "/Members/Carmel.jpg",
    Roles: "Secretary, graphic designer",
    phone: "",
    email: "",
  },
  {
    index: 9,
    name: "Bassim",
    imageAddress: "/Members/Bassim.jpg",
    Roles: "IT helper",
    phone: "",
    email: "",
  },
  {
    index: 10,
    name: "Radin",
    imageAddress: "/Members/Radin.jpg",
    Roles: "Project member",
    phone: "",
    email: "",
  },
  {
    index: 11,
    name: "Celine",
    imageAddress: "/Members/Celine.jpg",
    Roles: "Project member",
    phone: "",
    email: "",
  },
  {
    index: 12,
    name: "Kouroush",
    imageAddress: "/Members/Kouroush.jpg",
    Roles: "Project member",
    phone: "",
    email: "",
  },
  {
    index: 13,
    name: "Emaan",
    imageAddress: "/Members/Emaan.jpg",
    Roles: "Project member",
    phone: "",
    email: "",
  },
  {
    index: 14,
    name: "Kiarash",
    imageAddress: "/Members/Kiarash.jpg",
    Roles: "Multi-media manager",
    phone: "",
    email: "",
  },
  {
    index: 15,
    name: "Sama",
    imageAddress: "/Members/Sama.jpg",
    Roles: "Project member",
    phone: "",
    email: "",
  },
  {
    index: 16,
    name: "Nima",
    Roles: "Project member",
    phone: "",
    email: "",
  },
];
export default members;
